# Generated by Django 3.1.2 on 2021-01-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0004_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
