# Generated by Django 3.1.2 on 2021-01-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0005_auto_20210129_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='name',
        ),
    ]
