# Generated by Django 3.1.2 on 2021-03-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0006_auto_20210130_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
